# Generated by Django 6.0.6 on 2026-10-04 09:15

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.CharField(default=blog.utils.generate_cuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente se deixado em branco.', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Breve explicação do material para aparecer no card.', verbose_name='Descrição')),
                ('file', models.FileField(blank=True, help_text='Faça o upload caso seja um arquivo direto.', null=True, upload_to=blog.utils.get_materials_upload_path, verbose_name='Arquivo (PDF, Planilha, etc.)')),
                ('external_link', models.URLField(blank=True, help_text='Use caso o material esteja no Google Drive, Notion, Canva, etc.', null=True, verbose_name='Link Externo')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.utils.get_materials_upload_path, verbose_name='Imagem de Capa / Ilustração')),
                ('is_active', models.BooleanField(default=True, help_text='Marque para exibir este material na homepage e na página de materiais.', verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Materiais com menor número aparecem primeiro (0, 1, 2...).', verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
