# Generated by Django 6.0.6 on 2026-10-08 09:56

import blog.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=blog.utils.generate_cuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Comentário')),
                ('is_active', models.BooleanField(default=False, help_text='Marque para exibir este comentário.', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Post')),
            ],
        ),
    ]
